language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
services:
- postgresql
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- python manage.py migrate --settings=backend.settings.test
script:
- coverage run --source=app manage.py test --settings=backend.settings.test
- flake8 .
after_success: coveralls
notifications:
  slack:
    secure: P4pAqu1yIpijZi8hZGf2MB6+1DCLjreYgTCeoUBqy0eHHemcYc39cgQQ1p6icpf4vEeopK20R1pHGtBb73qn53+wGAlgPU3b1hSJVwSJwUkryDJavmMUVciDQdIMeigL1p4v1KnFwJXN42+dtrC5zXr4DJ0cQK098Ha4kCqGHaDZ4SUvB1Qa9Zvo5cL6mAF2CpyRPcqq9ggvKfuO0UZy67lYaTJyeDtDNRZY8OdyZ0ydQmb2zY1niA2BqRS9dYsBVeLR12fIh+wQX6hg1QZM2tLfRQvNF2kZ6O1HMwqXbzUWmQZIIsXtG8QJH9yuXPdtd1borFIyOATyA5ouRIey0vMK1jK9qFjY03PcD24icIi2KV3kGUJzfJFf7KWUPDoF6aHQJ1PIHtvotXlo/ySX9voZq0amjjTJp7ox8jRg/HLE7M8KV6Serryy0GVHCavnQr7L79hi5kCoxX6Wt097g25ltFhrx1qU/sZAS/rOUOpX5H4UuCHk6x7vqdUMkxNFtGGO/c2GfauUMGTFzCyP6tby1SBty/48uwrM0kApohw2ZWKIHsTwiSMybV+w4cqkHQDtko3Flks44IKIVlRbq6yJpeNAnF5zhjxk8wkzfBd/+t+NVbiwpG+KbqNHP+Uyn+T6u1VsntuO4UEQT7D6ijj0YZ2Pdk8InrSBc31Xbb0=
deploy:
  provider: heroku
  api_key:
    secure: KRyg9DW8N0P6vWD/jqINs8PzNHWdT+BUvjFpFX0atQwYymMVNdn/P2+3qXqwz27uOQxN4lOJovTAyUnfGkR3AZspkB47FUeq6AVP2enJDURvFkfav1O44yMcxaaccAF8AWCrPkbNU3rid0O04pA9wbcfdGnBPHpvA7Fawa5FqEiT1BddNWQ0PJES3PR72vAbgJ4dxv6o9YJ7eKDhflFPlPqx4+9KrVHPZNiybX2X6ms6+xMN00YPCn4cr9GXtZEJFrviNBjSm88LGCiSVbzhs9d/av3lXYV64YoYp6TcFgCorX6SuvolxLmKO+8aPYBn+v0PYAde1fvOmKxvN0zP1V3WwBy+LCVFVKhjFVpG7kl4JqZNImpdTfIX4bn9jfk9pmCHdVeYqir2M8RLtaoITc2sIGQ6akwoUKw6pWaSflpSq4WV1EXnnOJ/dxKuEAzDHdsJ47ubAgBqFPVOa8bSaYAHr2PNJDArcK/yXKvPoxG6B945s/rNmcZlzyP8DGKEHeEEtwdeSLFb0uT01ZQRBE3mMav7DWs0/KeDwUM89HZ6l2rBWOEkdSiYiOcOgP+pXtUr6e0X5MM5ZltMR6Ggz/bMbmK4mW5M4hPqMECW5rUsIuNquwQeIqMDQ5lMWixKyGs1fgxm+8zvTnrNFTP9TMX6oec4obLy+xpVve77/FU=
  app:
    master: mentorpaired
    staging: mentorpaired-staging
  run:
    - python manage.py migrate --noinput
