language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
services:
- postgresql
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- python manage.py migrate --settings=backend.settings.test
script:
- coverage run --source=app manage.py test --settings=backend.settings.test
- flake8 .
after_success: coveralls
notifications:
  slack:
    secure: P4pAqu1yIpijZi8hZGf2MB6+1DCLjreYgTCeoUBqy0eHHemcYc39cgQQ1p6icpf4vEeopK20R1pHGtBb73qn53+wGAlgPU3b1hSJVwSJwUkryDJavmMUVciDQdIMeigL1p4v1KnFwJXN42+dtrC5zXr4DJ0cQK098Ha4kCqGHaDZ4SUvB1Qa9Zvo5cL6mAF2CpyRPcqq9ggvKfuO0UZy67lYaTJyeDtDNRZY8OdyZ0ydQmb2zY1niA2BqRS9dYsBVeLR12fIh+wQX6hg1QZM2tLfRQvNF2kZ6O1HMwqXbzUWmQZIIsXtG8QJH9yuXPdtd1borFIyOATyA5ouRIey0vMK1jK9qFjY03PcD24icIi2KV3kGUJzfJFf7KWUPDoF6aHQJ1PIHtvotXlo/ySX9voZq0amjjTJp7ox8jRg/HLE7M8KV6Serryy0GVHCavnQr7L79hi5kCoxX6Wt097g25ltFhrx1qU/sZAS/rOUOpX5H4UuCHk6x7vqdUMkxNFtGGO/c2GfauUMGTFzCyP6tby1SBty/48uwrM0kApohw2ZWKIHsTwiSMybV+w4cqkHQDtko3Flks44IKIVlRbq6yJpeNAnF5zhjxk8wkzfBd/+t+NVbiwpG+KbqNHP+Uyn+T6u1VsntuO4UEQT7D6ijj0YZ2Pdk8InrSBc31Xbb0=
deploy:
  provider: heroku
  api_key:
    secure: v6ttBYYN0e2nuqjAdo2jM1aCiSxFzw/EhF/U1RDYYjA1ddaljBUTneSPqI0hAYEHitJrxj3BRNqqKKCdfAO728MQjMCBR5HTRsaUHsxoj3RZu4LKN9hMqtxOTFmroG3Sx/f/n98mdQ3wpi4IqDgSKU80rQC5GgzAhgI769qAJYWbpxhqYS7Ne6RxcfeHZUhFkVKLuvolBxOxETYT/JSqK3MuXaGnaPimbMb7Tvi9vfLRH1hDWCUERT0udpo2fwM34NvlWS5V5gwLoAWD0VGv6FUmSrwmPFrx6wHNd4dE/9O8Z+u5q5p7RxPaK3addPfOk+UYhlz/ipxP8F+SGyRHVv/n3uFGzBq/tcb8mFLB/4UYY3tJ73dSiWSnIP6u2uw1wuUyPc5De+K0vGSVa1pmN2JrBiT2iMWYSwj/BXRuSwgffVwXI/r19wnedT2VxuroAM852cKA0WOy3oSJwgxAhwZc8L0xgJvrKZNAtvpS1atyOW5dIRcxNqby9b067p8hhzppQi0W11UoYeO4es409jaAmEHyOwDbwl6jFagLbji2KBYKC9k7JGJ6dTmFl/09r9EobAXj17VewVE8lW84Z2I12406HHmTWMdgZvsh5/Vf3P3UvN4W5+FdDgv1JwGLPrJy5I2DUbS0XG3ni0e6Xhg6lY6kE/UPUR777ZvzTns=
  app:
    master: mentorpaired-backend
    staging: mentorpaired-staging-backend
  run:
  - python manage.py migrate --noinput
